"""expose insurance policy crud

Revision ID: 0634bd9da4cb
Revises: d5041011e2cf
Create Date: 2026-08-14 22:35:32.091781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0634bd9da4cb'
down_revision: Union[str, Sequence[str], None] = 'd5041011e2cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # household_member_role already exists (created by
    # a3f145ae6b6f for income_sources), so no CREATE TYPE is needed
    # here -- op.add_column() just references the existing type name.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'insurance_policies',
        sa.Column(
            'insured_owner',
            sa.Enum('CLIENT', 'SPOUSE', name='household_member_role'),
            nullable=False,
            server_default='CLIENT',
        ),
    )
    op.add_column('insurance_policies', sa.Column('policy_owner', sa.String(length=150), nullable=True))
    op.add_column('insurance_policies', sa.Column('beneficiary', sa.String(length=150), nullable=True))
    op.add_column('insurance_policies', sa.Column('surrender_value', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('insurance_policies', sa.Column('policy_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurance_policies', 'policy_year')
    op.drop_column('insurance_policies', 'surrender_value')
    op.drop_column('insurance_policies', 'beneficiary')
    op.drop_column('insurance_policies', 'policy_owner')
    op.drop_column('insurance_policies', 'insured_owner')
    # ### end Alembic commands ###
