"""add financial needs analysis intake

Revision ID: 4e8f938587ab
Revises: a3f145ae6b6f
Create Date: 2026-08-14 22:28:19.730714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8f938587ab'
down_revision: Union[str, Sequence[str], None] = 'a3f145ae6b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_needs_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('conducted_at', sa.Date(), nullable=False),
    sa.Column('has_monthly_budget', sa.Boolean(), nullable=True),
    sa.Column('has_regular_savings_plan', sa.Boolean(), nullable=True),
    sa.Column('monthly_savings_capacity', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('biggest_financial_concern', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('investment_knowledge', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'POOR', name='investor_rating'), nullable=True),
    sa.Column('risk_tolerance', sa.Enum('LOW', 'LOW_MEDIUM', 'MEDIUM', 'MEDIUM_HIGH', 'HIGH', name='risk_tolerance'), nullable=True),
    sa.Column('investment_experience', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'POOR', name='investor_rating'), nullable=True),
    sa.Column('priority_cash_flow', sa.Integer(), nullable=True),
    sa.Column('priority_protection', sa.Integer(), nullable=True),
    sa.Column('priority_retirement', sa.Integer(), nullable=True),
    sa.Column('priority_emergency_fund', sa.Integer(), nullable=True),
    sa.Column('priority_debt', sa.Integer(), nullable=True),
    sa.Column('priority_estate_preservation', sa.Integer(), nullable=True),
    sa.Column('wants_debt_payoff', sa.Boolean(), nullable=False),
    sa.Column('wants_income_replacement', sa.Boolean(), nullable=False),
    sa.Column('income_replacement_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('income_replacement_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('income_replacement_years', sa.Integer(), nullable=True),
    sa.Column('wants_mortgage_payoff', sa.Boolean(), nullable=False),
    sa.Column('wants_education_funding', sa.Boolean(), nullable=False),
    sa.Column('education_funding_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('wants_final_expenses', sa.Boolean(), nullable=False),
    sa.Column('final_expenses_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('wants_emergency_fund', sa.Boolean(), nullable=False),
    sa.Column('emergency_fund_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_needs_analyses_client_id'), 'financial_needs_analyses', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_needs_analyses_client_id'), table_name='financial_needs_analyses')
    op.drop_table('financial_needs_analyses')
    # ### end Alembic commands ###

    # Dropping a table doesn't cascade to the Postgres ENUM types it
    # used, so drop them explicitly (see 7e5f21fed89a for the same
    # pattern) so downgrade is fully reversible.
    enum_type_names = [
        "investor_rating",
        "risk_tolerance",
    ]
    bind = op.get_bind()
    for type_name in enum_type_names:
        sa.Enum(name=type_name).drop(bind, checkfirst=True)
