"""add financial plan api with action items

Revision ID: 53da8313ac12
Revises: 8cbd3cb9c8f7
Create Date: 2026-08-16 13:12:56.038209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53da8313ac12'
down_revision: Union[str, Sequence[str], None] = '8cbd3cb9c8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative_summary', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_plans_client_id'), 'financial_plans', ['client_id'], unique=False)
    op.create_table('financial_plan_action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_plan_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('EMERGENCY_FUND', 'DEBT_PAYOFF', 'INSURANCE', 'REGISTERED_ACCOUNT', 'RETIREMENT', 'GOAL', 'OTHER', name='action_item_category'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'DONE', name='action_item_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['financial_plan_id'], ['financial_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_plan_action_items_financial_plan_id'), 'financial_plan_action_items', ['financial_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_plan_action_items_financial_plan_id'), table_name='financial_plan_action_items')
    op.drop_table('financial_plan_action_items')
    op.drop_index(op.f('ix_financial_plans_client_id'), table_name='financial_plans')
    op.drop_table('financial_plans')
    # ### end Alembic commands ###

    # Dropping a table doesn't cascade to the Postgres ENUM types it
    # used, so drop them explicitly (see 7e5f21fed89a for the same
    # pattern) so downgrade is fully reversible.
    enum_type_names = [
        "action_item_category",
        "action_item_status",
    ]
    bind = op.get_bind()
    for type_name in enum_type_names:
        sa.Enum(name=type_name).drop(bind, checkfirst=True)
