"""link clients to advisors

Revision ID: 735fc1d5b8b0
Revises: a430ea22c8c0
Create Date: 2026-08-11 10:02:01.500562

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '735fc1d5b8b0'
down_revision: str | Sequence[str] | None = 'a430ea22c8c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('advisor_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_clients_advisor_id'), 'clients', ['advisor_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'advisors', ['advisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_advisor_id'), table_name='clients')
    op.drop_column('clients', 'advisor_id')
    # ### end Alembic commands ###
