"""add financial domain tables

Revision ID: 7e5f21fed89a
Revises: 735fc1d5b8b0
Create Date: 2026-08-11 18:20:03.917810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5f21fed89a'
down_revision: Union[str, Sequence[str], None] = '735fc1d5b8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.Enum('CHECKING', 'SAVINGS', 'INVESTMENT', 'RETIREMENT', 'CREDIT', 'LOAN', name='account_type'), nullable=False),
    sa.Column('institution', sa.String(length=150), nullable=True),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_client_id'), 'accounts', ['client_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('INCOME', 'HOUSING', 'UTILITIES', 'GROCERIES', 'DINING', 'TRANSPORTATION', 'HEALTHCARE', 'INSURANCE', 'ENTERTAINMENT', 'SAVINGS_TRANSFER', 'DEBT_PAYMENT', 'OTHER', name='transaction_category'), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='One budget row per client per category.'
    )
    op.create_index(op.f('ix_budgets_client_id'), 'budgets', ['client_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_advisor_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('STATEMENT', 'TAX_DOCUMENT', 'INSURANCE_POLICY', 'IDENTIFICATION', 'OTHER', name='document_category'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_advisor_id'], ['advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_advisor_id'), 'documents', ['uploaded_by_advisor_id'], unique=False)
    op.create_table('financial_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('goal_type', sa.Enum('EMERGENCY_FUND', 'RETIREMENT', 'HOME_PURCHASE', 'EDUCATION', 'DEBT_PAYOFF', 'OTHER', name='goal_type'), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'ABANDONED', name='goal_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_goals_client_id'), 'financial_goals', ['client_id'], unique=False)
    op.create_table('insurance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('policy_type', sa.Enum('TERM_LIFE', 'WHOLE_LIFE', 'DISABILITY', 'CRITICAL_ILLNESS', 'HEALTH', 'AUTO', 'HOME', 'OTHER', name='policy_type'), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('coverage_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('premium', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('premium_frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUALLY', name='premium_frequency'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'LAPSED', 'CANCELLED', name='policy_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_policies_client_id'), 'insurance_policies', ['client_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='task_status'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_advisor_id'), 'tasks', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_tasks_client_id'), 'tasks', ['client_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('merchant', sa.String(length=150), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.Enum('INCOME', 'HOUSING', 'UTILITIES', 'GROCERIES', 'DINING', 'TRANSPORTATION', 'HEALTHCARE', 'INSURANCE', 'ENTERTAINMENT', 'SAVINGS_TRANSFER', 'DEBT_PAYMENT', 'OTHER', name='transaction_category'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_tasks_client_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_advisor_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_insurance_policies_client_id'), table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_index(op.f('ix_financial_goals_client_id'), table_name='financial_goals')
    op.drop_table('financial_goals')
    op.drop_index(op.f('ix_documents_uploaded_by_advisor_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_budgets_client_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_accounts_client_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###

    # Alembic's autogenerated drop_table calls don't drop the Postgres ENUM
    # types they created (dropping a table doesn't cascade to types it used).
    # Drop them explicitly so downgrade is fully reversible and a later
    # upgrade doesn't fail with "type already exists".
    enum_type_names = [
        "account_type",
        "transaction_category",
        "goal_type",
        "goal_status",
        "policy_type",
        "premium_frequency",
        "policy_status",
        "document_category",
        "task_status",
    ]
    bind = op.get_bind()
    for type_name in enum_type_names:
        sa.Enum(name=type_name).drop(bind, checkfirst=True)
