"""add risk questionnaire api with public link

Revision ID: 8cbd3cb9c8f7
Revises: b3fd1dda9407
Create Date: 2026-08-15 19:36:40.779484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cbd3cb9c8f7'
down_revision: Union[str, Sequence[str], None] = 'b3fd1dda9407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # risk_tolerance already exists (created by 4e8f938587ab for
    # financial_needs_analyses). create_type is a Postgres-dialect-
    # specific flag that only reliably applies via postgresql.ENUM
    # (not the generic sa.Enum) -- without it, op.create_table() tries
    # to CREATE TYPE again and fails with "type already exists", unlike
    # op.add_column(), which never tries to create the type at all.
    risk_tolerance_enum = postgresql.ENUM(
        'LOW', 'LOW_MEDIUM', 'MEDIUM', 'MEDIUM_HIGH', 'HIGH',
        name='risk_tolerance', create_type=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('questions_version', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('risk_tolerance', risk_tolerance_enum, nullable=True),
    sa.Column('ai_summary', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_questionnaires_client_id'), 'risk_questionnaires', ['client_id'], unique=False)
    op.create_index(op.f('ix_risk_questionnaires_token'), 'risk_questionnaires', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_questionnaires_token'), table_name='risk_questionnaires')
    op.drop_index(op.f('ix_risk_questionnaires_client_id'), table_name='risk_questionnaires')
    op.drop_table('risk_questionnaires')
    # ### end Alembic commands ###
