"""add income source and debt tracking

Revision ID: a3f145ae6b6f
Revises: 75d9436310b0
Create Date: 2026-08-14 22:23:43.892468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f145ae6b6f'
down_revision: Union[str, Sequence[str], None] = '75d9436310b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('debt_type', sa.Enum('MORTGAGE_PRIMARY', 'MORTGAGE_SECONDARY_HELOC', 'AUTO_LOAN', 'STUDENT_LOAN', 'CREDIT_CARD', 'PERSONAL_LOAN', 'OTHER', name='debt_type'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('lender', sa.String(length=150), nullable=True),
    sa.Column('original_term_months', sa.Integer(), nullable=True),
    sa.Column('origination_year', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_payment', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('minimum_payment', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_client_id'), 'debts', ['client_id'], unique=False)
    op.create_table('income_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Enum('CLIENT', 'SPOUSE', name='household_member_role'), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'BIWEEKLY', 'SEMI_MONTHLY', 'MONTHLY', 'ANNUALLY', name='income_frequency'), nullable=False),
    sa.Column('net_takehome', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_future', sa.Boolean(), nullable=False),
    sa.Column('start_age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_sources_client_id'), 'income_sources', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_sources_client_id'), table_name='income_sources')
    op.drop_table('income_sources')
    op.drop_index(op.f('ix_debts_client_id'), table_name='debts')
    op.drop_table('debts')
    # ### end Alembic commands ###

    # Dropping a table doesn't cascade to the Postgres ENUM types it
    # used, so drop them explicitly (see 7e5f21fed89a for the same
    # pattern) so downgrade is fully reversible.
    enum_type_names = [
        "debt_type",
        "household_member_role",
        "income_frequency",
    ]
    bind = op.get_bind()
    for type_name in enum_type_names:
        sa.Enum(name=type_name).drop(bind, checkfirst=True)
