"""add discretionary flag and expense categories

Revision ID: b3fd1dda9407
Revises: c40ba5a83d7d
Create Date: 2026-08-15 00:13:07.469101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3fd1dda9407'
down_revision: Union[str, Sequence[str], None] = 'c40ba5a83d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'budgets',
        sa.Column(
            'is_discretionary',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    # ### end Alembic commands ###

    # TransactionCategory gained six new values (shared by Budget and
    # Transaction). SQLAlchemy's Enum column stores the Python enum
    # member's NAME (uppercase), not its .value -- see c40ba5a83d7d
    # for the same lesson learned the hard way on account_type.
    for new_value in (
        'CHILDCARE', 'SUBSCRIPTIONS', 'CHARITABLE_GIVING',
        'CLOTHING', 'PERSONAL_CARE', 'ALIMONY_CHILD_SUPPORT',
    ):
        op.execute(
            f"ALTER TYPE transaction_category ADD VALUE IF NOT EXISTS '{new_value}'"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres cannot DROP a single enum VALUE, so shrinking
    # transaction_category back to its original values isn't done
    # here -- see c40ba5a83d7d's downgrade() for the same caveat.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'is_discretionary')
    # ### end Alembic commands ###
