"""extend accounts for canadian registered types

Revision ID: c40ba5a83d7d
Revises: 0634bd9da4cb
Create Date: 2026-08-14 23:57:12.954735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40ba5a83d7d'
down_revision: Union[str, Sequence[str], None] = '0634bd9da4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # household_member_role already exists (created by
    # a3f145ae6b6f for income_sources), so no CREATE TYPE is needed.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'accounts',
        sa.Column(
            'owner',
            sa.Enum('CLIENT', 'SPOUSE', name='household_member_role'),
            nullable=False,
            server_default='CLIENT',
        ),
    )
    op.add_column('accounts', sa.Column('invest_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('accounts', sa.Column('monthly_contribution', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('accounts', sa.Column('resp_beneficiary_dependent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'accounts_resp_beneficiary_dependent_id_fkey',
        'accounts', 'dependents', ['resp_beneficiary_dependent_id'], ['id'],
    )
    # ### end Alembic commands ###

    # AccountType gained four Canadian registered-account values.
    # ALTER TYPE ... ADD VALUE is safe outside a checked transaction on
    # PG12+/PG17 here since no row references a new value in this same
    # migration.
    # SQLAlchemy's Enum column stores the Python enum member's NAME
    # (uppercase), not its .value, matching the existing
    # CHECKING/SAVINGS/... convention already used by this column.
    for new_value in ('TFSA', 'RRSP', 'FHSA', 'RESP'):
        op.execute(f"ALTER TYPE account_type ADD VALUE IF NOT EXISTS '{new_value}'")


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres cannot DROP a single enum VALUE, so shrinking
    # account_type back to its original 6 values isn't done here.
    # Downgrading past this revision while any account uses one of the
    # 4 new types would leave the column referencing a value the
    # shrunk type no longer has -- if that's ever needed, follow the
    # standard Postgres "shrink an enum" recipe (rename -> recreate ->
    # cast -> drop old type) by hand.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'accounts_resp_beneficiary_dependent_id_fkey', 'accounts', type_='foreignkey'
    )
    op.drop_column('accounts', 'resp_beneficiary_dependent_id')
    op.drop_column('accounts', 'monthly_contribution')
    op.drop_column('accounts', 'invest_rate')
    op.drop_column('accounts', 'owner')
    # ### end Alembic commands ###
