"""extend client with household planning fields

Revision ID: d5041011e2cf
Revises: 4e8f938587ab
Create Date: 2026-08-14 22:31:10.024470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5041011e2cf'
down_revision: Union[str, Sequence[str], None] = '4e8f938587ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # op.add_column(), unlike op.create_table(), does not auto-create a
    # new Postgres ENUM type -- create it explicitly first or the
    # ALTER TABLE below fails with "type marital_status does not exist".
    marital_status_enum = sa.Enum(
        'SINGLE', 'MARRIED', 'COMMON_LAW', 'DIVORCED', 'WIDOWED',
        name='marital_status',
    )
    marital_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('marital_status', marital_status_enum, nullable=True))
    op.add_column(
        'clients',
        sa.Column(
            'first_time_home_buyer',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column('clients', sa.Column('retirement_age', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('life_expectancy_age', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('desired_retirement_monthly_income', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('clients', sa.Column('desired_retirement_income_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'desired_retirement_income_percent')
    op.drop_column('clients', 'desired_retirement_monthly_income')
    op.drop_column('clients', 'life_expectancy_age')
    op.drop_column('clients', 'retirement_age')
    op.drop_column('clients', 'first_time_home_buyer')
    op.drop_column('clients', 'marital_status')
    op.drop_column('clients', 'date_of_birth')
    # ### end Alembic commands ###

    # Dropping a column doesn't cascade to the Postgres ENUM type it
    # used, so drop it explicitly (see 7e5f21fed89a for the same
    # pattern) so downgrade is fully reversible.
    sa.Enum(name="marital_status").drop(op.get_bind(), checkfirst=True)
