"""add tracked fund catalog and performance api

Revision ID: f690bc911c34
Revises: 53da8313ac12
Create Date: 2026-08-16 20:20:17.101955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f690bc911c34'
down_revision: Union[str, Sequence[str], None] = '53da8313ac12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('fund_type', sa.Enum('INDEX', 'ETF', 'MUTUAL_FUND', 'STOCK', 'OTHER', name='fund_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advisor_id', 'symbol')
    )
    op.create_index(op.f('ix_tracked_funds_advisor_id'), 'tracked_funds', ['advisor_id'], unique=False)
    op.create_table('client_tracked_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tracked_fund_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tracked_fund_id'], ['tracked_funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'tracked_fund_id')
    )
    op.create_index(op.f('ix_client_tracked_funds_client_id'), 'client_tracked_funds', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_tracked_funds_tracked_fund_id'), 'client_tracked_funds', ['tracked_fund_id'], unique=False)
    op.create_table('fund_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_fund_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracked_fund_id'], ['tracked_funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracked_fund_id', 'price_date')
    )
    op.create_index(op.f('ix_fund_price_history_tracked_fund_id'), 'fund_price_history', ['tracked_fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_price_history_tracked_fund_id'), table_name='fund_price_history')
    op.drop_table('fund_price_history')
    op.drop_index(op.f('ix_client_tracked_funds_tracked_fund_id'), table_name='client_tracked_funds')
    op.drop_index(op.f('ix_client_tracked_funds_client_id'), table_name='client_tracked_funds')
    op.drop_table('client_tracked_funds')
    op.drop_index(op.f('ix_tracked_funds_advisor_id'), table_name='tracked_funds')
    op.drop_table('tracked_funds')
    # ### end Alembic commands ###

    # Dropping a table doesn't cascade to the Postgres ENUM type it
    # used, so drop it explicitly (see 7e5f21fed89a for the same
    # pattern) so downgrade is fully reversible.
    sa.Enum(name="fund_type").drop(op.get_bind(), checkfirst=True)
